version: '3'

services:
  db:
    image: postgres
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build:
      context: .
      dockerfile: web.dockerfile
    image: yusufertekindit/ct-web
    ports:
      - "8000:8000"
    depends_on:
      - db

  airflow:
    build:
      context: .
      dockerfile: airflow.dockerfile
    image: yusufertekindit/ct-airflow
    ports:
      - "8080:8080"
