# Generated by Django 2.2.2 on 2019-06-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('start_date', models.DateField(help_text='The date a record first became relevant to a register.', null=True)),
                ('end_date', models.DateField(help_text='The date a record stopped being applicable.', null=True)),
                ('name', models.TextField(help_text='The commonly-used name of a record.')),
                ('official_name', models.TextField(help_text='The official or technical name of a record.')),
                ('country', models.TextField(help_text="The country's 2-letter ISO 3166-2 alpha2 code.", primary_key=True, serialize=False)),
                ('citizen_names', models.TextField(help_text="The name of a country's citizens.")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CountryTerritory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='The date a record first became relevant to a register.', null=True)),
                ('end_date', models.DateField(help_text='The date a record stopped being applicable.', null=True)),
                ('name', models.TextField(help_text='The commonly-used name of a record.')),
                ('official_name', models.TextField(help_text='The official or technical name of a record.')),
                ('country', models.TextField(help_text="The country's 2-letter ISO 3166-2 alpha2 code.", null=True)),
                ('territory', models.TextField(help_text="The territory's ISO 3166-1 alpha3 code.Unique codes have been created for territories that don't have an existing ISO code.", null=True)),
                ('citizen_names', models.TextField(help_text="The name of a country's citizens.", null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('name', models.TextField(help_text='Name of the executed task', primary_key=True, serialize=False)),
                ('latest_execution_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('start_date', models.DateField(help_text='The date a record first became relevant to a register.', null=True)),
                ('end_date', models.DateField(help_text='The date a record stopped being applicable.', null=True)),
                ('name', models.TextField(help_text='The commonly-used name of a record.')),
                ('official_name', models.TextField(help_text='The official or technical name of a record.')),
                ('territory', models.TextField(help_text="The territory's ISO 3166-1 alpha3 code.Unique codes have been created for territories that don't have an existing ISO code.", primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
